Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:06:47) [MSC v.1914 32 bit (Intel)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> import telegram
import os

#Folder where the backup file is located
path = '<Your path here>'

#Backup file name
file = str(os.listdir(path)).replace("['", "")
fileString = file.replace("']", "")

#Token generated by @BotFather on Telegram
my_token = '<Your token here>'

#Message
message = 'Backup of the file {} has been done successfully!'.format(fileString)

#Chat ID
chat_id = <Your id here>

def send(message, chat_id, token=my_token):

        #Send a message to the user's telegram specified from chat_id.
        #chat_id must be a number!
        bot = telegram.Bot(token=token)
        bot.sendMessage(chat_id=chat_id, text=message)

send(message, chat_id, my_token)
